window.FINANCIAL_FILING_SLIDES_EN = [
  {
    layout: "hero", kicker: "SHBI-GB 7343 · AI in Finance · Group 7",
    title: "Financial filing<br>extraction",
    body: `<p class="hero-subtitle">Use AI to find three material risks in an annual filing—and make every conclusion traceable to the source</p><div class="hero-thesis"><span>Question this deck answers</span><strong>Which workflow best balances completeness, speed, and traceability? The core idea is to let the model judge risks while a program handles exact quotations and page numbers.</strong></div><p class="byline">Heyang Li · Haoyu Zheng · Haisen Zhang</p>`,
    sources: [["Chinese report", "report/financial_filing_extraction_report_zh.md"]], notes: "Open with the task and the comparison objects; do not expand on model background."
  },
  {
    layout: "task", kicker: "01 · Success criteria", title: "Task: deliver three verifiable risks from the risk section of a 10-K",
    body: `<div class="task-grid"><div class="filing-sheet"><span>10-K · annual report filed by a U.S. public company</span><p><strong>Item 1A / Risk Factors:</strong> the section describing major threats to operations or financial performance.</p><mark>Input: a short excerpt from this section</mark></div><ol class="number-list"><li><span><strong>Select</strong> exactly three material risks—risks that could materially affect operations, cash flow, or losses</span></li><li><span><strong>Summarize</strong> each risk and its financial impact</span></li><li><span><strong>Assign</strong> one main type, such as regulatory, market, or operational</span></li><li><span><strong>Quote</strong> the supporting sentence verbatim</span></li><li><span><strong>Locate</strong> the paragraph and physical PDF page (the page number shown by the reader)</span></li></ol></div><p class="bottom-claim"><strong>Success = sound judgment + exact quotation + traceable location.</strong> A plausible-sounding answer is not enough.</p>`,
    sources: [["Task definition", "report/financial_filing_extraction_report_zh.md#1-先把任务说清楚"]], notes: "A material risk is not simply a sentence containing the word ‘material’; it has a clear operating or financial impact."
  },
  {
    layout: "manual-time", kicker: "02 · Assumed manual baseline", title: "Without AI: about 30 minutes for one short case",
    body: `<div class="manual-flow"><article><span>01</span><strong>Locate Item 1A</strong><em>3 min</em><p>Open the file and confirm the page number</p></article><b>→</b><article><span>02</span><strong>Read and mark</strong><em>10 min</em><p>Identify potentially material risks</p></article><b>→</b><article><span>03</span><strong>Select and classify</strong><em>6 min</em><p>Choose the top three and their primary types</p></article><b>→</b><article><span>04</span><strong>Copy evidence</strong><em>6 min</em><p>Transcribe the source text and page number</p></article><b>→</b><article><span>05</span><strong>Review and format</strong><em>5 min</em><p>Check quotations and format the output</p></article></div><div class="manual-summary"><span style="--share:53%"><strong>53%</strong> Reading + evidence copying</span><span style="--share:20%"><strong>20%</strong> Selection + classification</span><span style="--share:27%"><strong>27%</strong> Locating + review</span></div><div class="assumption-box"><strong>30 minutes is a scenario assumption, not an experimental measurement.</strong><p>Scope: a short 10-K risk case that is already prepared; document length, industry familiarity, and analytical depth will all change the actual time.</p></div>`,
    sources: [["Basis for task steps", "report/financial_filing_extraction_report_zh.md#14-模型必须交付什么"]], notes: "Make clear that these are transparent assumptions for classroom comparison."
  },
  {
    layout: "architecture", kicker: "03 · Three candidate solutions", title: "Same task; the difference is who judges and who copies exact fields",
    body: `<div class="figure-wrap"><img src="assets/final_solution_architectures.en.svg" alt="Three final workflows"></div><div class="workflow-labels"><span><strong>DeepSeek</strong> cloud general-purpose model writes the full answer</span><span><strong>Gemma</strong> local general-purpose model writes the full answer</span><span><strong>Finance pipeline</strong> finance model judges; a program copies quotes and pages</span></div><p class="reader-note architecture-note"><strong>A workflow means the model plus all preprocessing and validation around it.</strong> We compare complete solutions, not which model is “smarter” under one prompt.</p>`,
    sources: [["Workflow configuration", "harness/config/profiles.json"], ["Architecture overview", "report/financial_filing_extraction_report_zh.md#3-三条工作流的模型基础与职责设计"]], notes: "Compare complete solutions, not a leaderboard of bare models under the same prompt."
  },
  {
    layout: "simple-compare", kicker: "04 · Core design difference", title: "The first two constrain one model; the third splits work between model and program",
    body: `<div class="simple-columns"><article><span>DeepSeek</span><h3>Use a prompt—model instructions—to constrain output</h3><p>Require JSON: a machine-readable answer with fixed fields.</p><strong>Remaining issue: the model may still rewrite quotations</strong></article><article><span>Gemma</span><h3>Add a word-for-word self-check to the prompt</h3><p>Ask the model to verify every word and punctuation mark before adding locations.</p><strong>Remaining issue: slower, and locations can still fail</strong></article><article><span>Finance pipeline</span><h3>Model selects Evidence IDs—source-text numbers</h3><p>The program numbers each source passage; the model selects three numbers; the program restores exact text and pages.</p><strong>Design shift: model judges; program performs exact copying</strong></article></div>`,
    sources: [["DeepSeek PV016", "prompts/PV016.md"], ["Gemma PV015", "prompts/PV015.md"], ["Finance PV013", "prompts/PV013.md"]], notes: "Focus on how the three solutions differ; do not expand into every tuning version."
  },
  {
    layout: "result", kicker: "05 · Stability result · Frozen = no instruction or rule changes before testing", title: "Frozen-workflow test: Finance pipeline passes 3 / 3 completely",
    body: `<div class="figure-wrap result-figure"><img src="assets/02_blind_outcome_matrix.en.svg" alt="Results for three companies and three solutions"></div><div class="score-summary"><span>DeepSeek <strong>1 / 3</strong></span><span>Gemma <strong>2 / 3</strong></span><span>Finance pipeline <strong>3 / 3</strong></span></div><p class="reader-note"><strong>Complete pass = correct fixed format + exact quotation + valid paragraph/page location.</strong> 1/3 means one of three companies passed all three gates—not one correct risk or 33% financial accuracy.</p>`,
    sources: [["Review results", "report/data/reviewed_results.csv"], ["Experiment index", "experiments/INDEX.csv"]], notes: "A pass requires structure, verbatim evidence, and location to pass together."
  },
  {
    layout: "metric", kicker: "06 · Speed result", title: "Machine runtime: DeepSeek is fastest; Finance sits in the middle",
    body: `<div class="metric-layout"><div class="figure-wrap"><img src="assets/03_optimized_latency.en.svg" alt="Measured runtime of the three solutions"></div><div class="metric-copy"><p><span>DeepSeek</span><strong>Average 6.7 seconds</strong>Range 6.3–7.2 seconds</p><p><span>Finance</span><strong>Average 126.3 seconds</strong>Range 68.7–161.6 seconds</p><p><span>Gemma</span><strong>Average 209.1 seconds</strong>Range 156.5–239.5 seconds</p></div></div><p class="bottom-claim"><strong>The y-axis is logarithmic: equal height gaps mean equal ratios, not equal seconds; use the numbers on the right.</strong> Environments differ, so we compare total time from input through validation only within this experiment.</p>`,
    sources: [["Measured data", "report/data/reviewed_results.csv"]], notes: "Cloud DeepSeek is fastest, but speed and complete-pass rate must be considered separately."
  },
  {
    layout: "assisted-time", kicker: "07 · Put the previous machine time into one human workflow", title: "Under the same human-review assumption, roughly 30 minutes falls to 7–11 minutes",
    body: `<div class="time-bars"><div><span>Manual only</span><i style="--time:100%"></i><strong>30.0 min</strong></div><div><span>DeepSeek-assisted</span><i style="--time:24%"></i><strong>7.1 min</strong></div><div><span>Finance-assisted</span><i style="--time:30%"></i><strong>9.1 min</strong></div><div><span>Gemma-assisted</span><i style="--time:35%"></i><strong>10.5 min</strong></div></div><div class="savings-row"><span>DeepSeek <strong>−76%</strong></span><span>Finance <strong>−70%</strong></span><span>Gemma <strong>−65%</strong></span></div><div class="time-formula"><span>Same formula</span><strong>Total = 2 minutes preparation + previous measured runtime + 5 minutes review (DeepSeek ≈ 7.1 minutes)</strong></div><p class="reader-note"><strong>Correction time is not included.</strong> If the output does not pass completely, DeepSeek and Gemma require additional manual correction; this page is not a measured production-efficiency result.</p>`,
    sources: [["Machine runtime", "report/data/reviewed_results.csv"], ["Calculation convention", "presentation/README.md"]], notes: "Only machine runtime comes from the experiment; all other time is an explicit assumption."
  },
  {
    layout: "pipeline", kicker: "08 · Why Finance is more stable", title: "The model judges; the program handles exact quotations and page numbers",
    body: `<div class="pipeline-lanes"><div class="lane deterministic"><span>Program</span><strong>① Give every source passage an Evidence ID</strong><p>The number is tied to exact text · paragraph · PDF page</p></div><b>→</b><div class="lane model"><span>Finance model</span><strong>② Select 3 evidence numbers</strong><p>Write summary + category; do not copy quotations</p></div><b>→</b><div class="lane deterministic"><span>Program</span><strong>③ Restore source text by number</strong><p>Exact quotation · page · format validation</p></div></div><div class="ownership-grid"><p><span>Model is responsible</span><strong>Risk judgment and classification</strong></p><p><span>Program is responsible</span><strong>Source text, page number, and formatting</strong></p><p><span>Human is responsible</span><strong>Final financial plausibility review</strong></p></div><div class="responsibility-row"><span>No model retraining</span><strong>It is more stable because the program takes over error-prone exact copying—not because the model became smarter</strong></div>`,
    sources: [["Evidence Catalog", "scripts/lib/evidence_catalog.cjs"], ["Locator", "scripts/apply_evidence_locator.cjs"]], notes: "Evidence IDs are immutable references. The model makes the financial judgment; the program performs exact copying."
  },
  {
    layout: "jpm", kicker: "09 · Boundary of automatic evaluation", title: "Automatic pass proves a text match—not that the PDF page was parsed correctly",
    body: `<div class="figure-wrap jpm-figure"><img src="assets/jpm_two_column_failure.en.svg" alt="A two-column JPMorgan PDF causes extracted text to interleave"></div><div class="jpm-verdicts"><p><span>DeepSeek</span><strong>0 / 3 string matches</strong>Related content is still visible on the page</p><p><span>Gemma</span><strong>1 / 3 string matches</strong>One page number is also wrong</p><p><span>Finance</span><strong>3 / 3 string matches</strong>Yet copied text may mix both columns</p></div><p class="reader-note jpm-note"><strong>A human must still inspect the PDF page.</strong> Automatic checks compare strings; they do not understand two-column layout or financial meaning.</p>`,
    sources: [["R2/R3 summary", "experiments/R2_R3_OPTIMIZED_SUMMARY.md"], ["JPM page", "data/processed/case_packets/JPM-FY24/pages/page-016.png"]], notes: "Explain only why human review is still required."
  },
  {
    layout: "close", kicker: "10 · Decision", title: "With traceability as the priority, the most practical choice is<br>the Finance pipeline",
    body: `<div class="closing-evidence"><article><span>Stability</span><strong>3 / 3 companies passed completely</strong><p>Format, exact quotations, and locations are traceable</p></article><article><span>Time cost</span><strong>2.1 minutes average machine time</strong><p>Slower than DeepSeek, faster than Gemma</p></article><article><span>Why choose it</span><strong>It removes errors the model often makes</strong><p>Model judges; program owns exact fields</p></article></div><blockquote><strong>Decision rule: secure completeness and traceability first; compare speed second.</strong> DeepSeek is faster but passes 1/3 completely; Finance is slower but passes 3/3. We therefore choose Finance for this task—not because the small model itself is smarter.</blockquote><p class="thanks">Thank you · Questions welcome</p>`,
    sources: [["Full Chinese report", "report/financial_filing_extraction_report_zh.md"], ["Project repository", "https://github.com/Alhabor/financial-filing-extraction"]], notes: "End by repeating the solution choice, the time trade-off, and the reason."
  }
];
