window.FINANCIAL_FILING_SLIDES_EN = [
  {
    layout: "hero", kicker: "SHBI-GB 7343 · AI in Finance · Group 7",
    title: "Financial filing<br>extraction",
    body: `<p class="hero-subtitle">How three AI workflows identify, classify, and locate evidence for material 10-K risks</p><div class="hero-thesis"><span>Core takeaway</span><strong>The Finance small-model solution leads mainly because it splits the workflow—not because this experiment proves a gap in raw model capability.</strong></div><p class="byline">Heyang Li · Haoyu Zheng · Haisen Zhang</p>`,
    sources: [["Chinese report", "report/financial_filing_extraction_report_zh.md"]], notes: "Open with the task and the comparison objects; do not expand on model background."
  },
  {
    layout: "task", kicker: "Course task", title: "From one excerpt of 10-K text, deliver three verifiable risks",
    body: `<div class="task-grid"><div class="filing-sheet"><span>FORM 10-K · ITEM 1A</span><p>Input: a short excerpt from the Risk Factors section</p><mark>“identify three material risks”</mark></div><ol class="number-list"><li><span><strong>Select</strong> exactly three material risks</span></li><li><span><strong>Summarize</strong> each risk and its financial impact</span></li><li><span><strong>Assign</strong> one primary risk type</span></li><li><span><strong>Quote</strong> the supporting source text verbatim</span></li><li><span><strong>Locate</strong> the paragraph and physical PDF page</span></li></ol></div><p class="bottom-claim">A plausible-sounding answer is not enough; every judgment must be traceable to the source text.</p>`,
    sources: [["Task definition", "report/financial_filing_extraction_report_zh.md#1-先把任务说清楚"]], notes: "A material risk is not simply a sentence containing the word ‘material’; it has a clear operating or financial impact."
  },
  {
    layout: "manual-time", kicker: "Assumed baseline manual workflow", title: "Without AI: about 30 minutes for one short case",
    body: `<div class="manual-flow"><article><span>01</span><strong>Locate Item 1A</strong><em>3 min</em><p>Open the file and confirm the page number</p></article><b>→</b><article><span>02</span><strong>Read and mark</strong><em>10 min</em><p>Identify potentially material risks</p></article><b>→</b><article><span>03</span><strong>Select and classify</strong><em>6 min</em><p>Choose the top three and their primary types</p></article><b>→</b><article><span>04</span><strong>Copy evidence</strong><em>6 min</em><p>Transcribe the source text and page number</p></article><b>→</b><article><span>05</span><strong>Review and format</strong><em>5 min</em><p>Check quotations and format the output</p></article></div><div class="manual-summary"><span style="--share:53%"><strong>53%</strong> Reading + evidence copying</span><span style="--share:20%"><strong>20%</strong> Selection + classification</span><span style="--share:27%"><strong>27%</strong> Locating + review</span></div><div class="assumption-box"><strong>30 minutes is a scenario assumption, not an experimental measurement.</strong><p>Scope: a short 10-K risk case that is already prepared; document length, industry familiarity, and analytical depth will all change the actual time.</p></div>`,
    sources: [["Basis for task steps", "report/financial_filing_extraction_report_zh.md#14-模型必须交付什么"]], notes: "Make clear that these are transparent assumptions for classroom comparison."
  },
  {
    layout: "architecture", kicker: "Three AI solutions", title: "Same task, three models with different role assignments",
    body: `<div class="figure-wrap"><img src="assets/final_solution_architectures.en.svg" alt="Three final workflows"></div><div class="workflow-labels"><span><strong>DeepSeek</strong> cloud general-purpose model, generates the complete result directly</span><span><strong>Gemma</strong> local general-purpose model, generates the complete result directly</span><span><strong>Finance pipeline</strong> local finance-tuned small model, selects evidence and classifies only</span></div>`,
    sources: [["Workflow configuration", "harness/config/profiles.json"], ["Architecture overview", "report/financial_filing_extraction_report_zh.md#3-三条工作流的模型基础与职责设计"]], notes: "Compare complete solutions, not a leaderboard of bare models under the same prompt."
  },
  {
    layout: "simple-compare", kicker: "Solution differences", title: "The first two rely on prompt constraints; the third relies on pipeline decomposition",
    body: `<div class="simple-columns"><article><span>DeepSeek</span><h3>Prompt repairs the JSON</h3><p>Disable reasoning, define field types, and narrow the output scope.</p><strong>Remaining issue: quotations may still be rewritten</strong></article><article><span>Gemma</span><h3>Prompt adds a copy check</h3><p>Compare every word and punctuation mark before filling in paragraph and page numbers.</p><strong>Remaining issue: slow, and location can still fail</strong></article><article><span>Finance pipeline</span><h3>Model selects Evidence IDs only</h3><p>The program filters evidence, then restores the quotation and page number by ID.</p><strong>Design shift: exact fields are no longer freely generated</strong></article></div>`,
    sources: [["DeepSeek PV016", "prompts/PV016.md"], ["Gemma PV015", "prompts/PV015.md"], ["Finance PV013", "prompts/PV013.md"]], notes: "Focus on how the three solutions differ; do not expand into every tuning version."
  },
  {
    layout: "result", kicker: "After freezing · Pfizer / JPMorgan / Meta · single run, no retry", title: "Complete pass results across the three solutions",
    body: `<div class="figure-wrap result-figure"><img src="assets/02_blind_outcome_matrix.en.svg" alt="Results for three companies and three solutions"></div><div class="score-summary"><span>DeepSeek <strong>1 / 3</strong></span><span>Gemma <strong>2 / 3</strong></span><span>Finance pipeline <strong>3 / 3</strong></span></div><p class="reader-note"><strong>1/3 means one of three companies passed completely,</strong> not that only one risk was correct; it is not a 33% financial accuracy score.</p>`,
    sources: [["Review results", "report/data/reviewed_results.csv"], ["Experiment index", "experiments/INDEX.csv"]], notes: "A pass requires structure, verbatim evidence, and location to pass together."
  },
  {
    layout: "metric", kicker: "Measured machine time", title: "Runtime: DeepSeek is fastest; Finance sits in the middle",
    body: `<div class="metric-layout"><div class="figure-wrap"><img src="assets/03_optimized_latency.en.svg" alt="Measured runtime of the three solutions"></div><div class="metric-copy"><p><span>DeepSeek</span><strong>Average 6.7 seconds</strong>Range 6.3–7.2 seconds</p><p><span>Finance</span><strong>Average 126.3 seconds</strong>Range 68.7–161.6 seconds</p><p><span>Gemma</span><strong>Average 209.1 seconds</strong>Range 156.5–239.5 seconds</p></div></div><p class="bottom-claim">This is the measured end-to-end runtime of one complete workflow; the three solutions use different execution environments.</p>`,
    sources: [["Measured data", "report/data/reviewed_results.csv"]], notes: "Cloud DeepSeek is fastest, but speed and complete-pass rate must be considered separately."
  },
  {
    layout: "assisted-time", kicker: "Scenario time with AI assistance", title: "Under the same human-review assumption, roughly 30 minutes falls to 7–11 minutes",
    body: `<div class="time-bars"><div><span>Manual only</span><i style="--time:100%"></i><strong>30.0 min</strong></div><div><span>DeepSeek-assisted</span><i style="--time:24%"></i><strong>7.1 min</strong></div><div><span>Finance-assisted</span><i style="--time:30%"></i><strong>9.1 min</strong></div><div><span>Gemma-assisted</span><i style="--time:35%"></i><strong>10.5 min</strong></div></div><div class="savings-row"><span>DeepSeek <strong>−76%</strong></span><span>Finance <strong>−70%</strong></span><span>Gemma <strong>−65%</strong></span></div><div class="time-formula"><span>Shared assumption</span><strong>2 minutes of preparation + measured machine runtime + 5 minutes of human review</strong></div><p class="reader-note"><strong>Correction time is not included.</strong> If the output does not pass completely, DeepSeek and Gemma require additional manual correction; this page is not a measured production-efficiency result.</p>`,
    sources: [["Machine runtime", "report/data/reviewed_results.csv"], ["Calculation convention", "presentation/README.md"]], notes: "Only machine runtime comes from the experiment; all other time is an explicit assumption."
  },
  {
    layout: "pipeline", kicker: "Why Finance is more stable", title: "The model makes the judgment; the program preserves verbatim evidence",
    body: `<div class="pipeline-lanes"><div class="lane deterministic"><span>Program</span><strong>① Filter candidate evidence</strong><p>Complete sentence · paragraph · PDF page</p></div><b>→</b><div class="lane model"><span>Finance model</span><strong>② Select 3 Evidence IDs</strong><p>Summary · classification · no quotation generation</p></div><b>→</b><div class="lane deterministic"><span>Program</span><strong>③ Restore exactly by ID</strong><p>Verbatim quotation · page number · validation</p></div></div><div class="ownership-grid"><p><span>Model is responsible</span><strong>Risk judgment and classification</strong></p><p><span>Program is responsible</span><strong>Source text, page number, and formatting</strong></p><p><span>Human is responsible</span><strong>Final financial plausibility review</strong></p></div><div class="responsibility-row"><span>Model weights are unchanged</span><strong>By reducing the input and the responsibilities, the pipeline directly removes quotation and location errors</strong></div>`,
    sources: [["Evidence Catalog", "scripts/lib/evidence_catalog.cjs"], ["Locator", "scripts/apply_evidence_locator.cjs"]], notes: "Evidence IDs are immutable references. The model makes the financial judgment; the program performs exact copying."
  },
  {
    layout: "jpm", kicker: "One reminder we must keep", title: "An automatic pass does not prove that the source document was parsed correctly",
    body: `<div class="figure-wrap jpm-figure"><img src="assets/jpm_two_column_failure.en.svg" alt="A two-column JPMorgan PDF causes extracted text to interleave"></div><div class="jpm-verdicts"><p><span>DeepSeek</span><strong>0 / 3 quote matches</strong>Related content is still visible on the page</p><p><span>Gemma</span><strong>1 / 3 quote matches</strong>One page number is also wrong</p><p><span>Finance</span><strong>3 / 3 automatic matches</strong>Yet the extracted text is interleaved</p></div>`,
    sources: [["R2/R3 summary", "experiments/R2_R3_OPTIMIZED_SUMMARY.md"], ["JPM page", "data/processed/case_packets/JPM-FY24/pages/page-016.png"]], notes: "Explain only why human review is still required."
  },
  {
    layout: "close", kicker: "Conclusion", title: "For this task, the most practical choice is<br>the Finance pipeline",
    body: `<div class="closing-evidence"><article><span>Stability</span><strong>3 / 3 companies passed completely</strong><p>Structure, quotations, and locations are all traceable</p></article><article><span>Time</span><strong>2.1 minutes average machine time</strong><p>Slower than DeepSeek, faster than Gemma</p></article><article><span>Reason</span><strong>The workflow narrows the failure space</strong><p>The model no longer handles verbatim copying and page numbers</p></article></div><blockquote>The conclusion is not “the small model beat the large models.” It is: for a focused task, assigning responsibilities is more effective than continuing to stack prompt constraints.</blockquote><p class="thanks">Thank you · Questions welcome</p>`,
    sources: [["Full Chinese report", "report/financial_filing_extraction_report_zh.md"], ["Project repository", "https://github.com/Alhabor/financial-filing-extraction"]], notes: "End by repeating the solution choice, the time trade-off, and the reason."
  }
];
