window.FINANCIAL_FILING_SLIDES_EN = [
  {
    layout: "hero", kicker: "SHBI-GB 7343 · AI in Finance · Group 7",
    title: "Financial filing<br>extraction",
    body: `<p class="hero-subtitle">Use AI to find three material risks in an annual filing—and make every conclusion traceable to the source</p><div class="hero-thesis"><span>Question this deck answers</span><strong>Which workflow best balances completeness, speed, and traceability? The core idea is to let the model judge risks while a program handles exact quotations and page numbers.</strong></div><div class="hero-contract"><p><span>Compare</span><strong>DeepSeek · Gemma · Finance pipeline</strong></p><p><span>Deliver</span><strong>3 risks · exact quotations · PDF locations</strong></p><p><span>Decision order</span><strong>Completeness first · speed second</strong></p></div><p class="byline">Heyang Li · Haoyu Zheng · Haisen Zhang</p>`,
    sources: [["English report", "report/financial_filing_extraction_report_en.md"]], notes: "Open with the task and the comparison objects; do not expand on model background."
  },
  {
    layout: "task", kicker: "01 · Success criteria", title: "Task: deliver three verifiable risks from the risk section of a 10-K",
    body: `<div class="task-grid"><div class="filing-sheet"><span>10-K · annual report filed by a U.S. public company</span><p><strong>Item 1A / Risk Factors:</strong> the formal section disclosing threats that could materially harm the business, operating results, or financial condition.</p><div class="filing-contract"><p><span>Input</span><strong>An excerpt from Item 1A</strong></p><p><span>Output</span><strong>Exactly three structured risks</strong></p><p><span>Evidence</span><strong>Each risk links to a sentence, paragraph, and physical PDF page</strong></p></div><div class="term-notes"><p><strong>Material risk</strong> does not mean finding the word <code>material</code>; it means judging whether the disclosed effect could materially harm business or financial results.</p><p><strong>Physical page</strong> is the page sequence shown by the PDF reader, which may differ from the printed page number.</p></div><div class="output-record"><span>One passing record contains</span><p><b>risk_summary</b><strong>Risk + financial consequence</strong></p><p><b>category</b><strong>One primary risk type</strong></p><p><b>evidence_quote</b><strong>An exact supporting sentence</strong></p><p><b>location</b><strong>Paragraph ID + physical PDF page</strong></p></div></div><ol class="number-list"><li><span><strong>Select</strong> exactly three material risks—risks that could materially affect operations, cash flow, or losses</span></li><li><span><strong>Summarize</strong> each risk and its financial impact</span></li><li><span><strong>Assign</strong> one main type, such as regulatory, market, or operational</span></li><li><span><strong>Quote</strong> the supporting sentence verbatim, without paraphrasing</span></li><li><span><strong>Locate</strong> its paragraph and physical PDF page so a reader can verify it</span></li></ol></div><p class="bottom-claim"><strong>Success = sound judgment + exact quotation + traceable location.</strong> A plausible-sounding answer is not enough.</p>`,
    sources: [["Task definition", "report/financial_filing_extraction_report_zh.md#1-先把任务说清楚"]], notes: "A material risk is not simply a sentence containing the word ‘material’; it has a clear operating or financial impact."
  },
  {
    layout: "manual-time", kicker: "02 · Assumed manual baseline", title: "Without AI: about 30 minutes for one short case",
    body: `<div class="manual-flow"><article><span>01</span><strong>Locate Item 1A</strong><em>3 min</em><p>Open the file and confirm the page number</p></article><b>→</b><article><span>02</span><strong>Read and mark</strong><em>10 min</em><p>Identify potentially material risks</p></article><b>→</b><article><span>03</span><strong>Select and classify</strong><em>6 min</em><p>Choose the top three and their primary types</p></article><b>→</b><article><span>04</span><strong>Copy evidence</strong><em>6 min</em><p>Transcribe the source text and page number</p></article><b>→</b><article><span>05</span><strong>Review and format</strong><em>5 min</em><p>Check quotations and format the output</p></article></div><div class="manual-summary"><span style="--share:53%"><strong>53%</strong> Reading + evidence copying</span><span style="--share:20%"><strong>20%</strong> Selection + classification</span><span style="--share:27%"><strong>27%</strong> Locating + review</span></div><div class="assumption-box"><strong>30 minutes is a scenario assumption, not an experimental measurement.</strong><p>Scope: a short 10-K risk case that is already prepared; document length, industry familiarity, and analytical depth will all change the actual time.</p></div>`,
    sources: [["Basis for task steps", "report/financial_filing_extraction_report_zh.md#14-模型必须交付什么"]], notes: "Make clear that these are transparent assumptions for classroom comparison."
  },
  {
    layout: "architecture", kicker: "03 · Three candidate solutions", title: "Same task; the difference is who judges and who copies exact fields",
    body: `<div class="figure-wrap"><img src="assets/final_solution_architectures.en.svg" alt="Three final workflows"></div><div class="workflow-labels"><span><strong>DeepSeek</strong> cloud general-purpose model writes the full answer</span><span><strong>Gemma</strong> local general-purpose model writes the full answer</span><span><strong>Finance pipeline</strong> finance model judges; a program copies quotes and pages</span></div><p class="reader-note architecture-note"><strong>A workflow means the model plus all preprocessing and validation around it.</strong> We compare complete solutions, not which model is “smarter” under one prompt.</p>`,
    sources: [["Workflow configuration", "harness/config/profiles.json"], ["Architecture overview", "report/financial_filing_extraction_report_zh.md#3-三条工作流的模型基础与职责设计"]], notes: "Compare complete solutions, not a leaderboard of bare models under the same prompt."
  },
  {
    layout: "simple-compare", kicker: "04 · Core design difference", title: "The first two constrain one model; the third splits work between model and program",
    body: `<div class="simple-columns"><article><span>DeepSeek</span><h3>Use model instructions to constrain output</h3><p class="method-copy">The model reads the case and generates three risks, categories, JSON, quotations, and locations in one pass.</p><dl class="design-details"><div><dt>Judgment</dt><dd>Model</dd></div><div><dt>Exact copying</dt><dd>Model</dd></div><div><dt>Main advantage</dt><dd>Fastest cloud run</dd></div></dl><strong>Remaining issue: a fixed format does not stop the model from paraphrasing quotations</strong></article><article><span>Gemma</span><h3>Add a word-for-word self-check</h3><p class="method-copy">The local model checks every word and punctuation mark in six steps before adding paragraph and page locations.</p><dl class="design-details"><div><dt>Judgment</dt><dd>Model</dd></div><div><dt>Exact copying</dt><dd>Model self-check</dd></div><div><dt>Main advantage</dt><dd>Files stay local</dd></div></dl><strong>Remaining issue: slower, and locations can still fail</strong></article><article><span>Finance pipeline</span><h3>Model selects source-text Evidence IDs</h3><p class="method-copy">A program numbers candidate passages; the model selects three IDs; the program restores exact text, paragraphs, and pages.</p><dl class="design-details"><div><dt>Judgment</dt><dd>Finance model</dd></div><div><dt>Exact copying</dt><dd>Deterministic code</dd></div><div><dt>Main advantage</dt><dd>Exact fields are guaranteed</dd></div></dl><strong>Design shift: the model judges; code handles work that must be exact</strong></article></div>`,
    sources: [["DeepSeek PV016", "prompts/PV016.md"], ["Gemma PV015", "prompts/PV015.md"], ["Finance PV013", "prompts/PV013.md"]], notes: "Focus on how the three solutions differ; do not expand into every tuning version."
  },
  {
    layout: "result", kicker: "05 · Stability result · Frozen = no instruction or rule changes before testing", title: "Frozen-workflow test: Finance pipeline passes 3 / 3 completely",
    body: `<div class="figure-wrap result-figure"><img src="assets/02_blind_outcome_matrix.en.svg" alt="Results for three companies and three solutions"></div><div class="score-summary"><span>DeepSeek <strong>1 / 3</strong></span><span>Gemma <strong>2 / 3</strong></span><span>Finance pipeline <strong>3 / 3</strong></span></div><p class="reader-note"><strong>Complete pass = correct fixed format + exact quotation + valid paragraph/page location.</strong> 1/3 means one of three companies passed all three gates—not one correct risk or 33% financial accuracy.</p>`,
    sources: [["Review results", "report/data/reviewed_results.csv"], ["Experiment index", "experiments/INDEX.csv"]], notes: "A pass requires structure, verbatim evidence, and location to pass together."
  },
  {
    layout: "metric", kicker: "06 · Speed result", title: "Machine runtime: DeepSeek is fastest; Finance sits in the middle",
    body: `<div class="metric-layout"><div class="figure-wrap"><img src="assets/03_optimized_latency.en.svg" alt="Measured runtime of the three solutions"></div><div class="metric-copy"><p><span>DeepSeek</span><strong>Average 6.7 seconds</strong>Range 6.3–7.2 seconds</p><p><span>Finance</span><strong>Average 126.3 seconds</strong>Range 68.7–161.6 seconds</p><p><span>Gemma</span><strong>Average 209.1 seconds</strong>Range 156.5–239.5 seconds</p></div></div><p class="bottom-claim"><strong>The y-axis is logarithmic: equal height gaps mean equal ratios, not equal seconds; use the numbers on the right.</strong> Environments differ, so we compare total time from input through validation only within this experiment.</p>`,
    sources: [["Measured data", "report/data/reviewed_results.csv"]], notes: "Cloud DeepSeek is fastest, but speed and complete-pass rate must be considered separately."
  },
  {
    layout: "assisted-time", kicker: "07 · Put the previous machine time into one human workflow", title: "Under the same human-review assumption, roughly 30 minutes falls to 7–11 minutes",
    body: `<div class="time-bars"><div><span>Manual only</span><i style="--time:100%"></i><strong>30.0 min</strong></div><div><span>DeepSeek-assisted</span><i style="--time:24%"></i><strong>7.1 min</strong></div><div><span>Finance-assisted</span><i style="--time:30%"></i><strong>9.1 min</strong></div><div><span>Gemma-assisted</span><i style="--time:35%"></i><strong>10.5 min</strong></div></div><div class="savings-row"><article><header><span>DeepSeek</span><strong>−76%</strong></header><p>Saves <strong>22.9 minutes</strong> vs. manual</p><small>Assumed total: 7.1 minutes</small></article><article><header><span>Finance</span><strong>−70%</strong></header><p>Saves <strong>20.9 minutes</strong> vs. manual</p><small>Assumed total: 9.1 minutes</small></article><article><header><span>Gemma</span><strong>−65%</strong></header><p>Saves <strong>19.5 minutes</strong> vs. manual</p><small>Assumed total: 10.5 minutes</small></article></div><div class="time-formula"><span>Same formula</span><strong>Total = 2 minutes preparation + previous measured runtime + 5 minutes review (DeepSeek ≈ 7.1 minutes)</strong></div><div class="reader-note assisted-caveat"><strong>Scenario estimate—not measured production efficiency</strong><p><strong>Correction time is excluded.</strong> DeepSeek and Gemma need extra manual repair when an output does not pass completely, so actual time may be longer.</p></div>`,
    sources: [["Machine runtime", "report/data/reviewed_results.csv"], ["Calculation convention", "presentation/README.md"]], notes: "Only machine runtime comes from the experiment; all other time is an explicit assumption."
  },
  {
    layout: "pipeline", kicker: "08 · Why Finance is more stable", title: "The model judges; the program handles exact quotations and page numbers",
    body: `<div class="pipeline-lanes"><div class="lane deterministic"><span>Program</span><strong>① Give every source passage an Evidence ID</strong><p>The number is tied to exact text · paragraph · PDF page</p></div><b>→</b><div class="lane model"><span>Finance model</span><strong>② Select 3 evidence numbers</strong><p>Write summary + category; do not copy quotations</p></div><b>→</b><div class="lane deterministic"><span>Program</span><strong>③ Restore source text by number</strong><p>Exact quotation · page · format validation</p></div></div><div class="ownership-grid"><p><span>Model is responsible</span><strong>Risk judgment and classification</strong></p><p><span>Program is responsible</span><strong>Source text, page number, and formatting</strong></p><p><span>Human is responsible</span><strong>Final financial plausibility review</strong></p></div><div class="responsibility-row"><span>No model retraining</span><strong>It is more stable because the program takes over error-prone exact copying—not because the model became smarter</strong></div>`,
    sources: [["Evidence Catalog", "scripts/lib/evidence_catalog.cjs"], ["Locator", "scripts/apply_evidence_locator.cjs"]], notes: "Evidence IDs are immutable references. The model makes the financial judgment; the program performs exact copying."
  },
  {
    layout: "jpm", kicker: "09 · Boundary of automatic evaluation", title: "Automatic pass proves a text match—not that the PDF page was parsed correctly",
    body: `<div class="figure-wrap jpm-figure"><img src="assets/jpm_two_column_failure.en.svg" alt="A two-column JPMorgan PDF causes extracted text to interleave"></div><div class="jpm-verdicts"><p><span>DeepSeek</span><strong>0 / 3 string matches</strong>Related content is still visible on the page</p><p><span>Gemma</span><strong>1 / 3 string matches</strong>One page number is also wrong</p><p><span>Finance</span><strong>3 / 3 string matches</strong>Yet copied text may mix both columns</p></div><p class="reader-note jpm-note"><strong>A human must still inspect the PDF page.</strong> Automatic checks compare strings; they do not understand two-column layout or financial meaning.</p>`,
    sources: [["R2/R3 summary", "experiments/R2_R3_OPTIMIZED_SUMMARY.md"], ["JPM page", "data/processed/case_packets/JPM-FY24/pages/page-016.png"]], notes: "Explain only why human review is still required."
  },
  {
    layout: "close", kicker: "10 · Decision", title: "With traceability as the priority, the most practical choice is<br>the Finance pipeline",
    body: `<div class="closing-evidence"><article><span>Stability</span><strong>3 / 3 companies passed completely</strong><p>Format, exact quotations, and locations are traceable; DeepSeek passes 1 / 3 and Gemma 2 / 3.</p></article><article><span>Time cost</span><strong>2.1 minutes average machine time</strong><p>Slower than DeepSeek at 6.7 seconds and faster than Gemma at 3.5 minutes; these are end-to-end times in this experiment.</p></article><article><span>Source of the advantage</span><strong>Fewer exact-copying errors</strong><p>The model judges risks; code restores quotations, paragraphs, and pages; a human still reviews financial meaning.</p></article></div><blockquote><strong>Decision rule: secure completeness and traceability first; compare speed second.</strong> We choose the Finance pipeline for this task because its division of responsibility fits the task—not because the small model itself is smarter.</blockquote><div class="decision-boundary"><p><span>Use it when</span><strong>The task can be split and requires fixed fields, verbatim evidence, and reliable locations</strong></p><p><span>It still cannot guarantee</span><strong>Correct two-column PDF parsing, sufficient evidence, or the most defensible risk category</strong></p></div><p class="thanks">Thank you · Questions welcome</p>`,
    sources: [["Full English report", "report/financial_filing_extraction_report_en.md"], ["Project repository", "https://github.com/Alhabor/financial-filing-extraction"]], notes: "End by repeating the solution choice, the time trade-off, and the reason."
  }
];
